import { useEffect, useState } from 'react';
import {
  validThickness,
  type WallArtSettings,
  type WallMaterial,
  wallMaterials,
  wallThicknessLimits,
} from './wallArt';

export type WallArtState = WallArtSettings & {
  thickness: number;
  error: string;
};

export function WallArtControls({
  wallArt,
  busy,
  change,
}: {
  wallArt: WallArtState;
  busy: boolean;
  change: (changes: Partial<WallArtSettings> & { thickness?: number }) => void;
}) {
  const [draft, setDraft] = useState(String(wallArt.thickness));
  useEffect(() => setDraft(String(wallArt.thickness)), [wallArt.thickness]);
  const value = Number(draft);
  const invalid = !validThickness(value);
  function commit() {
    if (!invalid && value !== wallArt.thickness) change({ thickness: value });
    else setDraft(String(wallArt.thickness));
  }
  return (
    <fieldset className="wall-art" aria-label="Walls and doors artwork">
      <legend>Walls &amp; doors</legend>
      <p className="hint">
        Drawn from room and door geometry above all artwork, and included in
        exports. Not generated by AI.
      </p>
      <label className="inline">
        <input
          type="checkbox"
          checked={wallArt.visible}
          disabled={busy}
          onChange={(e) => change({ visible: e.target.checked })}
        />
        Show walls and doors
      </label>
      <label>
        Material
        <select
          value={wallArt.material}
          disabled={busy}
          onChange={(e) => change({ material: e.target.value as WallMaterial })}
        >
          {wallMaterials.map((material) => (
            <option key={material} value={material}>
              {material[0].toUpperCase() + material.slice(1)}
            </option>
          ))}
        </select>
      </label>
      <label>
        Thickness (map units)
        <input
          type="number"
          min={wallThicknessLimits.min}
          max={wallThicknessLimits.max}
          step="1"
          value={draft}
          disabled={busy}
          aria-invalid={invalid}
          onChange={(e) => setDraft(e.target.value)}
          onBlur={commit}
          onKeyDown={(e) => {
            if (e.key === 'Enter') {
              e.preventDefault();
              commit();
            }
          }}
        />
      </label>
      {invalid && (
        <p role="alert">
          Enter {wallThicknessLimits.min}–{wallThicknessLimits.max} map units.
        </p>
      )}
      {wallArt.error && <p role="alert">{wallArt.error}</p>}
    </fieldset>
  );
}
