"""Deterministic wall/door artwork rendered from geometry, never generated by AI.

Native geometry is bottom-left/+y-up; image rows point down. The output is a
transparent RGBA overlay composited above all raster artwork (ADR-0030).
"""

import math
from functools import lru_cache
from typing import Annotated, Any, Literal

import numpy as np
import shapely  # type: ignore[import-untyped]
from PIL import Image, ImageChops, ImageDraw
from pydantic import Field, JsonValue
from shapely.geometry import LinearRing, LineString, Polygon, box  # type: ignore[import-untyped]
from shapely.ops import unary_union  # type: ignore[import-untyped]

from quill.doors import DoorInput, validate_doors
from quill.models import Contract, Door, Project, Wall
from quill.raster import native_to_pixel
from quill.walls import RoomBoundary, WallDerivationRequest, derive_walls

RENDERER = "quill-wall-art-v1"
MATERIALS = ("stone", "timber", "plaster")
Material = Literal["stone", "timber", "plaster"]
MIN_THICKNESS, MAX_THICKNESS = 1.0, 50.0
# Exported artwork sizes plus the editor's sharper on-screen preview.
RENDER_SIZES = {(480, 320), (960, 640), (1200, 800), (2400, 1600)}
SETTINGS_KEY = "quill.wallArt"
DEFAULT_SETTINGS: dict[str, JsonValue] = {"visible": True, "material": "stone"}

# Base wall-top colour and texture contrast per material.
PALETTES: dict[str, tuple[tuple[int, int, int], float]] = {
    "stone": ((116, 112, 104), 0.34),
    "timber": ((112, 78, 48), 0.26),
    "plaster": ((196, 186, 166), 0.16),
}
WALL_ART_PROMPT = (
    "Walls and doors are drawn separately over the room edges. Paint only the floor "
    "and furnishings, continuing the floor right up to the boundary. Do not paint "
    "walls, door frames or doorways.\n"
)
DOOR_COLOR, DOOR_EDGE = (138, 96, 56), (52, 34, 20)
GLASS_COLOR = (182, 210, 222)


class WallArtSettings(Contract):
    visible: bool
    material: Material


class WallArtRequest(Contract):
    contractVersion: Literal["0.1.0"] = "0.1.0"
    width: Annotated[int, Field(gt=0)]
    height: Annotated[int, Field(gt=0)]
    thickness: Annotated[float, Field(ge=MIN_THICKNESS, le=MAX_THICKNESS)]
    material: Material
    rooms: Annotated[list[RoomBoundary], Field(max_length=128)]
    doors: Annotated[list[DoorInput], Field(max_length=1024)]


def wall_art_settings(project: Project) -> WallArtSettings:
    """Absent settings mean the default visible stone treatment."""
    raw = project.settings.get(SETTINGS_KEY, DEFAULT_SETTINGS)
    if not isinstance(raw, dict):
        raise ValueError("Wall art settings must be an object.")
    try:
        return WallArtSettings.model_validate(raw)
    except ValueError as error:
        raise ValueError("Wall art settings require visible and a supported material.") from error


def validate_thickness(thickness: float) -> None:
    if not MIN_THICKNESS <= thickness <= MAX_THICKNESS:
        raise ValueError(
            f"Wall thickness must be between {MIN_THICKNESS:g} and {MAX_THICKNESS:g} map units."
        )


def _noise(
    size: tuple[int, int], map_size: tuple[float, float], cell: tuple[float, float], seed: int
) -> np.ndarray:
    """Seeded value noise on a native-unit lattice, bicubically resampled to the output.

    The lattice depends only on map size, cell and seed, so texture placement is
    stable across raster resolutions.
    """
    columns = max(2, math.ceil(map_size[0] / cell[0]) + 1)
    rows = max(2, math.ceil(map_size[1] / cell[1]) + 1)
    lattice = np.random.default_rng(seed).random((rows, columns), dtype=np.float32)
    # Rows run top-down in both lattice and image space.
    resized = Image.fromarray(lattice, "F").resize(size, Image.Resampling.BICUBIC)
    return np.asarray(resized)


@lru_cache(maxsize=8)
def _texture(material: str, size: tuple[int, int], map_size: tuple[float, float]) -> Image.Image:
    if material == "timber":
        # Long grain along x with finer planks across y.
        value = 0.6 * _noise(size, map_size, (18.0, 2.0), 7) + 0.4 * _noise(
            size, map_size, (3.0, 3.0), 11
        )
    else:
        value = (
            0.55 * _noise(size, map_size, (7.0, 7.0), 3)
            + 0.30 * _noise(size, map_size, (3.0, 3.0), 5)
            + 0.15 * _noise(size, map_size, (1.5, 1.5), 9)
        )
    color, contrast = PALETTES[material]
    shade = 1 - contrast / 2 + contrast * value
    rgb = np.clip(shade[..., None] * np.asarray(color, np.float32), 0, 255).astype(np.uint8)
    return Image.fromarray(rgb, "RGB")


def _rim_array(inside: np.ndarray, width: int) -> np.ndarray:
    """Cells of `inside` within `width` (4-connected) steps of its edge."""
    eroded = inside.copy()
    for _ in range(width):
        core = eroded.copy()
        core[1:, :] &= eroded[:-1, :]
        core[:-1, :] &= eroded[1:, :]
        core[:, 1:] &= eroded[:, :-1]
        core[:, :-1] &= eroded[:, 1:]
        eroded = core
    return inside & ~eroded


def _rim(mask: Image.Image, width: int) -> Image.Image:
    return Image.fromarray(_rim_array(np.asarray(mask) > 127, width).astype(np.uint8) * 255, "L")


def _polygons(geometry: Any) -> list[Polygon]:
    if geometry.is_empty:
        return []
    if isinstance(geometry, Polygon):
        return [geometry]
    return [part for item in geometry.geoms for part in _polygons(item)]


def _coverage_window(
    geometry: Any, size: tuple[int, int], map_size: tuple[float, float]
) -> tuple[tuple[int, int, int, int], Image.Image] | None:
    """Binary pixel-center coverage (raster.polygon_mask convention) in a pixel window.

    ImageDraw rounds vertices, so it only proposes candidates; Shapely decides
    each candidate exactly. Polygons are drawn separately so holes never erase
    other (nested) polygons. Returns the window box and its coverage.
    """
    if geometry.is_empty:
        return None
    min_x, min_y, max_x, max_y = geometry.bounds
    left, top = native_to_pixel(min_x, max_y, size, map_size)
    right, bottom = native_to_pixel(max_x, min_y, size, map_size)
    box_ = (
        max(0, math.floor(left) - 3),
        max(0, math.floor(top) - 3),
        min(size[0], math.ceil(right) + 3),
        min(size[1], math.ceil(bottom) + 3),
    )
    if box_[2] <= box_[0] or box_[3] <= box_[1]:
        return None
    window = (box_[2] - box_[0], box_[3] - box_[1])
    rough = Image.new("L", window)
    for polygon in _polygons(geometry):
        local = Image.new("L", window)
        draw = ImageDraw.Draw(local)
        for ring, fill in [(polygon.exterior, 255)] + [(hole, 0) for hole in polygon.interiors]:
            draw.polygon(
                [(x - box_[0], y - box_[1]) for x, y in _pixels(ring.coords, size, map_size)],
                fill=fill,
            )
        rough = ImageChops.lighter(rough, local)
    # Rounding moves edges by at most one pixel; widen the candidate band by two.
    candidates = np.asarray(rough) > 0
    candidates = candidates | _rim_array(~candidates, 2)
    rows, columns = np.nonzero(candidates)
    covered = np.zeros(candidates.shape, dtype=np.uint8)
    if rows.size:
        x = (columns + box_[0] + 0.5) * map_size[0] / size[0]
        y = map_size[1] - (rows + box_[1] + 0.5) * map_size[1] / size[1]
        shapely.prepare(geometry)
        covered[rows, columns] = shapely.intersects_xy(geometry, x, y) * 255
    return box_, Image.fromarray(covered, "L")


def _coverage(geometry: Any, size: tuple[int, int], map_size: tuple[float, float]) -> Image.Image:
    full = Image.new("L", size)
    window = _coverage_window(geometry, size, map_size)
    if window:
        full.paste(window[1], window[0][:2])
    return full


def _pixels(
    coords: Any, size: tuple[int, int], map_size: tuple[float, float]
) -> list[tuple[float, float]]:
    return [native_to_pixel(x, y, size, map_size) for x, y in coords]


def _frame(wall: Wall) -> tuple[float, float, float, float, float]:
    dx, dy = wall.end.x - wall.start.x, wall.end.y - wall.start.y
    length = math.hypot(dx, dy)
    return wall.start.x, wall.start.y, dx / length, dy / length, length


def _rectangle(
    wall: Wall, low: float, high: float, half_depth: float, offset: float = 0.0
) -> Polygon:
    """Rectangle along a wall between distances low/high, centered offset from the line."""
    x, y, ux, uy, _ = _frame(wall)
    nx, ny = -uy, ux
    return Polygon(
        [
            (x + ux * s + nx * (offset + d), y + uy * s + ny * (offset + d))
            for s, d in (
                (low, -half_depth),
                (high, -half_depth),
                (high, half_depth),
                (low, half_depth),
            )
        ]
    )


def wall_geometry(
    rooms: list[RoomBoundary],
    walls: list[Wall],
    doors: list[Door],
    thickness: float,
    map_size: tuple[float, float],
) -> Any:
    """Union of mitred room-boundary bands, minus visible door openings."""
    half = thickness / 2
    body = unary_union(
        [
            LinearRing([(p.x, p.y) for p in room.polygon]).buffer(
                half, join_style="mitre", mitre_limit=2.0
            )
            for room in rooms
        ]
    )
    by_id = {wall.id: wall for wall in walls}
    openings = []
    for door in doors:
        if door.secret or door.doorType != "door":
            continue
        wall = by_id[door.wallId]
        center = door.position * _frame(wall)[4]
        opening = _rectangle(wall, center - door.width / 2, center + door.width / 2, half + 0.5)
        # Never notch a perpendicular wall that meets the opening's end.
        others = [
            LineString([(w.start.x, w.start.y), (w.end.x, w.end.y)]).buffer(half, cap_style="flat")
            for w in walls
            if w.id != wall.id
        ]
        openings.append(opening.difference(unary_union(others)) if others else opening)
    if openings:
        body = body.difference(unary_union(openings))
    return body.intersection(box(0, 0, *map_size))


def _door_features(
    walls: list[Wall], doors: list[Door], thickness: float
) -> list[tuple[Polygon, tuple[int, int, int]]]:
    by_id = {wall.id: wall for wall in walls}
    leaf = max(thickness * 0.6, 3.0) / 2
    features: list[tuple[Polygon, tuple[int, int, int]]] = []
    for door in doors:
        if door.secret:
            continue  # Secret doors are deliberately indistinguishable from wall.
        wall = by_id[door.wallId]
        center = door.position * _frame(wall)[4]
        low, high = center - door.width / 2, center + door.width / 2
        if door.doorType == "window":
            features.append(
                (_rectangle(wall, low, high, max(thickness * 0.5, 1.5) / 2), GLASS_COLOR)
            )
        elif door.state == "open":
            # Leaf swung 90 degrees on the low-end hinge, toward the wall's left normal.
            x, y, ux, uy, _ = _frame(wall)
            hx, hy = x + ux * low, y + uy * low
            nx, ny = -uy, ux
            features.append(
                (
                    Polygon(
                        [
                            (hx + ux * a + nx * b, hy + uy * a + ny * b)
                            for a, b in (
                                (0, 0),
                                (2 * leaf, 0),
                                (2 * leaf, door.width),
                                (0, door.width),
                            )
                        ]
                    ),
                    DOOR_COLOR,
                )
            )
        else:
            features.append((_rectangle(wall, low, high, leaf), DOOR_COLOR))
            if door.state == "locked":
                bar = max(thickness * 0.6, 1.5) / 2
                features.append((_rectangle(wall, center - bar, center + bar, bar), DOOR_EDGE))
    return features


def render_wall_art(
    rooms: list[RoomBoundary],
    walls: list[Wall],
    doors: list[Door],
    *,
    thickness: float,
    material: str,
    size: tuple[int, int],
    map_size: tuple[float, float] = (1200.0, 800.0),
) -> Image.Image:
    """Return a transparent RGBA wall/door overlay at the requested raster size."""
    validate_thickness(thickness)
    if material not in MATERIALS:
        raise ValueError("Unsupported wall material.")
    if size not in RENDER_SIZES:
        raise ValueError("Unsupported wall art size.")
    if not rooms:
        return Image.new("RGBA", size)
    # Supersample small outputs so diagonal edges are antialiased.
    ss = 2 if size[0] <= 1200 else 1
    work = (size[0] * ss, size[1] * ss)
    mask = _coverage(wall_geometry(rooms, walls, doors, thickness, map_size), work, map_size)
    rgb = _texture(material, work, map_size).copy()
    # Darken a thin rim so walls read clearly against any floor artwork.
    rgb.paste((36, 32, 28), mask=_rim(mask, ss).point(lambda v: int(v * 0.7)))
    for polygon, color in _door_features(walls, doors, thickness):
        window = _coverage_window(polygon, work, map_size)
        if window is None:
            continue
        box_, feature = window
        rgb.paste(color, box_, feature)
        rgb.paste(DOOR_EDGE, box_, _rim(feature, ss))
        mask.paste(255, box_, feature)
    result = rgb.convert("RGBA")
    result.putalpha(mask)
    if ss > 1:
        result = result.resize(size, Image.Resampling.BOX)
    # Clear colour under full transparency: identical composite, far smaller PNGs.
    pixels = np.array(result)
    pixels[pixels[..., 3] == 0] = 0
    return Image.fromarray(pixels, "RGBA")


def project_wall_art(project: Project, size: tuple[int, int]) -> Image.Image | None:
    """Wall art for a validated project, or None when hidden."""
    settings = wall_art_settings(project)
    if not settings.visible:
        return None
    return render_wall_art(
        [RoomBoundary(id=room.id, polygon=room.polygon) for room in project.rooms],
        project.walls,
        project.doors,
        thickness=project.map.style.wallThicknessPx,
        material=settings.material,
        size=size,
        map_size=(project.map.width, project.map.height),
    )


def render_request(request: WallArtRequest) -> Image.Image:
    size = (request.width, request.height)
    if size not in RENDER_SIZES:
        raise ValueError("Unsupported wall art size.")
    walls = derive_walls(WallDerivationRequest(width=1200, height=800, rooms=request.rooms)).walls
    doors: list[Door] = [Door.model_validate(door.model_dump()) for door in request.doors]
    validate_doors(doors, walls)
    return render_wall_art(
        request.rooms,
        walls,
        doors,
        thickness=request.thickness,
        material=request.material,
        size=size,
    )
